name: action
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: make install
      - name: format
        run: make format
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: run
        run: make run